title: Quentin's log
email: qdeslandes@naccy.de
url: "https://naccy.de"
github_username:  qdeslandes

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  cpp:
    output: true
    permalink: /cpp/:path/
